// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: keyper.sql

package data

import (
	"context"
)

const getDecryptionKey = `-- name: GetDecryptionKey :one

SELECT dk.decryption_key
FROM decryption_key dk
INNER JOIN identity_registered_event ire
ON ire.eon = dk.eon AND ire.identity = dk.epoch_id
WHERE ire.identity = $1 AND ire.decrypted = TRUE
`

// write sql queries here
func (q *Queries) GetDecryptionKey(ctx context.Context, identity []byte) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDecryptionKey, identity)
	var decryption_key []byte
	err := row.Scan(&decryption_key)
	return decryption_key, err
}
