// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: keyper.sql

package data

import (
	"context"
)

const getDecryptionKey = `-- name: GetDecryptionKey :one

SELECT eon, epoch_id, decryption_key FROM decryption_key
WHERE eon = $1 AND epoch_id = $2
`

type GetDecryptionKeyParams struct {
	Eon     int64
	EpochID []byte
}

// write sql queries here
func (q *Queries) GetDecryptionKey(ctx context.Context, arg GetDecryptionKeyParams) (DecryptionKey, error) {
	row := q.db.QueryRow(ctx, getDecryptionKey, arg.Eon, arg.EpochID)
	var i DecryptionKey
	err := row.Scan(&i.Eon, &i.EpochID, &i.DecryptionKey)
	return i, err
}

const getDecryptionKeyForIdentity = `-- name: GetDecryptionKeyForIdentity :one
SELECT dk.decryption_key
FROM decryption_key dk
INNER JOIN identity_registered_event ire
ON ire.eon = dk.eon AND ire.identity = dk.epoch_id
WHERE ire.identity = $1 AND ire.decrypted = TRUE
`

func (q *Queries) GetDecryptionKeyForIdentity(ctx context.Context, identity []byte) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDecryptionKeyForIdentity, identity)
	var decryption_key []byte
	err := row.Scan(&decryption_key)
	return decryption_key, err
}
