// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package data

type DecryptionKey struct {
	Eon           int64
	EpochID       []byte
	DecryptionKey []byte
}

type IdentityRegisteredEvent struct {
	BlockNumber    int64
	BlockHash      []byte
	TxIndex        int64
	LogIndex       int64
	Eon            int64
	IdentityPrefix []byte
	Sender         string
	Timestamp      int64
	Decrypted      bool
	Identity       []byte
}
